### ISSUE TITLE
sftd config path error

### ISSUE THREAD

**Issue by jmatsushita** [wireapp/wire-docs#189]
There's an error in the docs https://docs.wire.com/how-to/install/sft.html#as-part-of-the-wire-server-umbrella-chart
```
brig:
  optSettings:
    setSftStaticUrl: "https://sftd.example.com:443"
```

is correct for the brig chart values, but since we use the `wire-server` umbrella chart it should be instead:

```
brig:
  config:
    optSettings:
      setSftStaticUrl: "https://sftd.example.com:443"
```
