### ISSUE TITLE
demo verification email not received

### ISSUE THREAD

**Issue by tofutim** [wireapp/wire-docs#56]
I'm pleased to report that my servers are up and running and I am able to access my demo wireapp page. However, when I go to create users and it attempts to send the 6 digit code, I never receive it in my email. Is there another step I am missing to setup the mail server?

Everything is internal so maybe that is the problem...

**Update.** I put everything external and still I get no email. Is there some setup of the mail server that needs to happen? Maybe ports beside 80 and 443 that need to be open or routed? Or, maybe the demo-smtp server is not supposed to work? I see in values.yaml
```
    smtp:
      host: demo-smtp # change this if you want to use your own SMTP server
      port: 25        # change this
      connType: plain # change this. Possible values: plain|ssl|tls
```
and in secrets.yaml
```
    smtpPassword: dummyPassword
```
I presume these are the default values for the demo-smtp server, but maybe they are not?

Another related question. Let's say I give up on the dummy smtp and decide to switch to my gmail smtp. Is there a way to update values without having to delete and redeploy?
