### ISSUE TITLE
Misleading tinc documentation

### ISSUE THREAD

**Issue by wire-user** [wireapp/wire-docs#77]
The documentation for [tinc](https://github.com/wireapp/wire-docs/blob/master/src/how-to/install/ansible-tinc.rst#L28) suggests 10.10.1.XXX and 10.10.1.YYY respectively as example IPs but the default netmask of the role uses 255.255.255.0 as netmask.

Changing it to 10.0.0.XXX would be less misleading. In addition to that the ansible role used to roll out tinc creates tinc-up and tinc-down scripts based on ifconfig which is deprecated and unmaintained and breaks on newer distros.

I've expanded the tinc.yml as a workaround playbook using this [gist](https://gist.github.com/davidbeauchamp/dada6acfb8fc94869175aa774825af35)

**tinc.yml**
```yaml
- name: Provision tinc server
  hosts: vpn
  environment: "{{ proxy_env | default({}) }}"
  vars:
    tinc_build_root: "{{ hostvars['localhost']['build_dir'] }}"
    # CHANGE THIS if your default network interface is not eth0
    physical_ip: "{{ ansible_enp1s0.ipv4.address }}"
  roles:
    - ansible-tinc
  tasks:
    - template:
        src: "tinc-up.j2"
        dest: "/etc/tinc/vpn0/tinc-up"
    - template:
        src: "tinc-down.j2"
        dest: "/etc/tinc/vpn0/tinc-down"
```

**templates/tinc-up.j2**
```sh
#!/bin/sh
ip link set $INTERFACE up
ip addr add {{vpn_ip}}/32 dev $INTERFACE
ip route add 10.0.0.0/24 dev $INTERFACE
```

**templates/tinc-down.j2**
```sh
#!/bin/sh
ip route del 10.0.0.0/24 dev $INTERFACE
ip addr del {{vpn_ip}}/32 dev $INTERFACE
ip link set $INTERFACE down
```
